### ISSUE TITLE
fail to git clone https://gitlab.svail.baidu.com/steve/action-segmentation-DA.git

### ISSUE THREAD

**Issue by chenwenhe11** [cmhungsteve/SSTDA#10]
fatal: unable to access 'https://gitlab.svail.baidu.com/steve/action-segmentation-DA.git/': Could not resolve host: gitlab.svail.baidu.com

**Comment by cmhungsteve** [comment]
updated the readme.

**Comment by chenwenhe11** [comment]
@cmhungsteve Thanks !
