### ISSUE TITLE
 Video Feature Extraction

### ISSUE THREAD

**Issue by lionel-hing** [cmhungsteve/SSTDA#2]
How to process I3D features dimension into (XXX, 2048)？XXX represents the number of video frames? This I3D feature only uses RGB or flow and RGB？

**Comment by cmhungsteve** [comment]
XXX represents frame number.
I3D uses both RGB and flow.

**Comment by lionel-hing** [comment]
> XXX represents frame number.
> I3D uses both RGB and flow.



> XXX represents frame number.
> I3D uses both RGB and flow.

Thank you! Thanks for your work!
