### ISSUE TITLE
Incomplete dataset Download

### ISSUE THREAD

**Issue by lvv93** [cmhungsteve/SSTDA#4]
Hello. 
Thank you so much for the files and code you uploaded. However, many times I downloaded the Dataset folder, it was incomplete. Could you please divide the Dataset file into several small compressed files and upload them? Thank you very much for your cooperation.
Best regards

**Comment by lvv93** [comment]
Hello,
I have successfully downloaded the Dataset folder. Please ignore this comment.
Best regards

**Comment by cmhungsteve** [comment]
I also divide the dataset into multiple files.
Thank you for your suggestion.
