### ISSUE TITLE
I3D Feature

### ISSUE THREAD

**Issue by Alen-T** [cmhungsteve/SSTDA#5]
Each video feature dimension：（2048，X）， Whether the feature dimension of each frame extracted is 2048？ or divide the video into X frames, and then extract all the frames with a special frame (2048, X)?
I3D doesn't seem to be able to extract features from a single frame,  so， I want to know how you extract features from a video.  Can you provide code to extract features? Thank you very much!

**Comment by cmhungsteve** [comment]
I used the features provided by MS-TCN.
You can check how they extract features here: https://github.com/yabufarha/ms-tcn/issues/16.
Although you cannot extract I3D features using a single frame, you can utilize neighbor frames.
For example, to extract a feature representing frame n, we can use a video clip with frames [n-7,n+7].
