### ISSUE TITLE
Qualitative results

### ISSUE THREAD

**Issue by houzhijian** [cmhungsteve/SSTDA#7]
Hi, steve:

Can you share the code or script that you use to produce those visualization results?

**Comment by cmhungsteve** [comment]
Unfortunately, I don't have the script at my hand.
The co-author produced all the visualization results.
However, there should be many similar scripts you can find online.
You just need to assign each class with the color you want, and then you can convert the frame-level predictions into segmentation visualization.

**Comment by houzhijian** [comment]
Hi, steve:

Thank you for your quick response.
The problem is that I don't know how to find similar scripts.
Could you give me some hints about keywords or links of some similar scripts?

**Comment by houzhijian** [comment]
Hi, steve:

Thank you.
I figure it out. plt.imshow will work.

**Comment by wwdok** [comment]
@houzhijian Hi, could you please share the srcipt ? thanks !

**Comment by houzhijian** [comment]
@wwdok I delete it on my side. You can learn from this

https://github.com/colincsl/TemporalConvolutionalNetworks/blob/cccdf868ed4c7a56745b41d30fd9f1dc637eb3f3/code/utils.py#L12

**Comment by wwdok** [comment]
@houzhijian OK,  thank you ！
